service: nc-news-sls

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-2
  memorySize: 128
  apiKeys:
    - apikey

functions:
  seed:
    handler: handlerTable.seed
    events:
      - http:
          path: /seed
          method: post
          cors: true
          private: true

  dropTable:
    handler: handlerTable.dropTable
    events:
      - http:
          path: /dropTable
          method: delete
          cors: true
          private: true

  createTable:
    handler: handlerTable.createTable
    events:
      - http:
          path: /createTable
          method: post
          cors: true
          private: true

  getTopics:
    handler: handler.getTopics
    events:
      - http:
          path: /topics
          method: get
          cors: true
