service: nc-news-sls

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-2
  memorySize: 128
  apiKeys:
    - apikey

functions:
  seed:
    handler: handler.seed
    events:
      - http:
          path: /seed
          method: post
          cors: true
          private: true

  dropTable:
    handler: handler.dropTable
    events:
      - http:
          path: /dropTable
          method: delete
          cors: true
          private: true

  createTable:
    handler: handler.createTable
    events:
      - http:
          path: /createTable
          method: post
          cors: true
          private: true

  createCommentsTable:
    handler: handler.createCommentsTable
    events:
      - http:
          path: /createCommentsTable
          method: post
          cors: true
          private: true
