service: nc-news-sls

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-2
  memorySize: 128
  apiKeys:
    - apikey

functions:
  seed:
    handler: handler.seed
    events:
      - http:
          path: /seed
          method: post
          cors: true
          private: true

resources: # CloudFormation template syntax from here on.
  Resources:
    topicsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: topicsTable
        AttributeDefinitions:
          - AttributeName: slug
            AttributeType: S
        KeySchema:
          - AttributeName: slug
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
